# Generated by Django 5.0.1 on 2024-01-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='category',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
